language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - make deps
  - make deps-test
script:
  - coverage run --source=batfish runtests.py
after_success:
  - coveralls
  - curl -X POST https://readthedocs.org/build/batfish
